// Auto-generated icon description map
export const iconDescriptions: Record<string, string> = {
  "AlignCenter": "align center | center align, middle align",
  "AlignJustify": "justify | full width text, block align",
  "AlignLeft": "align left | left align, flush left",
  "AlignRight": "align right | right align, flush right",
  "AlignVerticalBottom": "align bottom | snap to bottom, vertical align",
  "AlignVerticalCenter": "align middle | center vertically, vertical align",
  "AlignVerticalTop": "align top | snap to top, vertical align",
  "App": "app grid | modules, app gallery",
  "ArrowDown": "move down | descend, collapse, drop",
  "ArrowDownDot": "download point | download target, destination",
  "ArrowDownFill": "download | arrow down, descend",
  "ArrowIn": "import | ingest, inbound, data ingestion",
  "ArrowLeft": "back | previous, return",
  "ArrowOver": "skip | jump over, pass, skip step",
  "ArrowRight": "expand | forward, next, proceed",
  "ArrowsConnect": "Connection | Unity Catalog | linked, joined, related",
  "ArrowsUpDown": "sort | reorder, swap, toggle sort",
  "ArrowUp": "move up | ascend, expand, rise",
  "ArrowUpDot": "upload point | upload target, destination",
  "ArrowUpFill": "upload | arrow up, ascend",
  "Assistant": "Databricks Assistant | AI | chatbot, help agent",
  "At": "mention | tag user, @, email, handle",
  "AzHorizontal": "sort A-Z | alphabetical, ascending text",
  "AzVertical": "sort A-Z | alphabetical vertical, ascending text",
  "Backup": "backup | restore, snapshot, recovery",
  "BadgeCode": "Embedded credential | IAM | code badge, run as owner",
  "BadgeCodeOff": "No embedded credential | Platform | run as viewer, no code badge",
  "BarChart": "bar chart | AI/BI | trend, histogram, column chart",
  "BarGrouped": "Grouped bar chart | AI/BI | clustered bars, side by side",
  "BarsAscendingHorizontal": "sort ascending | low to high, increasing",
  "BarsAscendingVertical": "sort ascending | low to high, increasing",
  "BarsDescendingHorizontal": "sort descending | high to low, decreasing",
  "BarsDescendingVertical": "sort descending | high to low, decreasing",
  "BarStacked": "Stacked bar chart | AI/BI | cumulative bar, layered",
  "BarStackedPercentage": "Percentage bar chart | AI/BI | 100% stacked, proportional",
  "Beaker": "Experiment | AI | flask, lab, test, training",
  "Binary": "Binary | Data Type | boolean, true/false, bits",
  "Blockquote": "blockquote | quote, citation, callout",
  "Bold": "bold | strong text, heavy font",
  "Book": "Glossary | Unity Catalog | documentation, manual, guide, reference",
  "Bookmark": "bookmark | save, favorite, flag",
  "BookmarkFill": "bookmarked | saved, favorited, flagged",
  "Books": "Library | Platform | collection, manuals",
  "BracketsCheck": "valid code | syntax ok, code verified",
  "BracketsCurly": "JSON | Data Type | curly braces, code syntax",
  "BracketsError": "code error | syntax fail, code invalid",
  "BracketsSquare": "Array | Data Type | list, square brackets",
  "BracketsX": "invalid code | code error, syntax fail",
  "Branch": "Branch | Workspace | git branch, fork, version control",
  "BranchCheck": "branch merged | repos, git, approved, PR merged",
  "BranchReset": "reset branch | repos, git, revert, undo branch",
  "Briefcase": "Bundle | Workspace | DAB, suitcase, work",
  "BriefcaseFill": "Bundle | Workspace | DAB, suitcase, work",
  "Brush": "format | style, paint, customize",
  "Bug": "Bug | Platform | error, defect, debug, issue",
  "Calendar": "date | schedule, date picker",
  "CalendarClock": "Timestamp | Data Type | scheduled time, deadline, timed event",
  "CalendarEvent": "Scheduled event | Lakeflow | appointment, calendar item",
  "CalendarRange": "date range | date picker, period selector, timespan",
  "CalendarSync": "synced schedule | synchronized, auto-refresh",
  "Camera": "screenshot | capture, snapshot, photo",
  "CaretDownSquare": "dropdown | expand, select, caret down",
  "CaretUpSquare": "collapse | close dropdown, caret up",
  "Catalog": "Catalog | Unity Catalog | data container, database",
  "CatalogCloud": "Remote Catalog | Unity Catalog | remote catalog, foreign catalog",
  "CatalogGear": "System catalog | Unity Catalog | internal catalog",
  "CatalogHome": "Home Catalog | Unity Catalog | default catalog, primary",
  "CatalogOff": "Disabled catalog | Unity Catalog | unavailable, restricted",
  "CatalogShared": "Delta Shared Catalog | Unity Catalog | shared, collaborative, Delta Sharing",
  "CatalogUserHome": "Personal catalog | Unity Catalog | my catalog, user home",
  "CellsSquare": "table cells | grid cells, matrix",
  "Certified": "Certified | verified, approved, badge, endorsed",
  "CertifiedFill": "Certified | verified, approved, badge, endorsed",
  "CertifiedFillSmall": "Certified | verified, approved, badge, endorsed",
  "Chain": "Connect | Unity Catalog | chain, link, connection",
  "ChartLine": "line chart | AI/BI | trend, time series",
  "Check": "accept | checkmark, confirm, done",
  "Checkbox": "checkbox | toggle, boolean, multi-select",
  "CheckCircle": "success | success, complete, passed, healthy",
  "CheckCircleBadge": "active | online, healthy",
  "CheckCircleFill": "success | success, complete, passed, healthy",
  "CheckCircleSmall": "success | complete, passed, check",
  "CheckLine": "partial success | partial check, some complete",
  "Checklist": "list | task, to do, requirements",
  "CheckSmall": "accept | checkmark, confirm, done",
  "ChevronDoubleDown": "expand all | unfold all, open all",
  "ChevronDoubleLeft": "jump to start | first page, skip left",
  "ChevronDoubleLeftOff": "collapse disabled | can't collapse further",
  "ChevronDoubleRight": "jump to end | last page, skip right",
  "ChevronDoubleRightOff": "expand disabled | can't expand further",
  "ChevronDoubleUp": "collapse all | fold all, minimize all",
  "ChevronDown": "open menu | expand, dropdown",
  "ChevronLeft": "back | previous, navigate left",
  "ChevronRight": "expand tree | forward, next, more",
  "ChevronUp": "collapse | collapse, close menu, fold",
  "Chip": "Hardware | Compute | GPU, processor, accelerator",
  "Circle": "health | dot, status",
  "CircleOff": "offline | inactive, stopped, terminated, down",
  "CircleOffLarge": "offline | inactive, stopped, terminated",
  "CircleOutline": "unavailable | empty, unselected, idle",
  "CircleOutlineLarge": "incomplete | stepper step, not done, pending",
  "Clipboard": "paste | clipboard, buffer, copy to clipboard",
  "Clock": "schedule | time, history, recent, schedule",
  "ClockKey": "Temporary credential | Unity Catalog | time-limited key, expiring token",
  "ClockOff": "expired | timed out, schedule off, no schedule",
  "Close": "close | dismiss, x, cancel, remove",
  "CloseSmall": "close | dismiss, x, cancel, remove",
  "Cloud": "Metastore | Unity Catalog | cloud, hosted, remote",
  "CloudDatabase": "SQL Warehouse | Compute | remote processing, hosted compute",
  "CloudDownload": "download from cloud | fetch, pull, cloud sync",
  "CloudKey": "Cloud Credentials | Unity Catalog | cloud access key, provider key",
  "CloudModel": "Model serving endpoint | AI | cloud, model, api, endpoint",
  "CloudOff": "offline | disconnected, no cloud, unavailable",
  "CloudUpload": "upload to cloud | push, deploy, cloud sync",
  "Code": "Code | Platform | source, script, angle brackets",
  "ColorFill": "color fill | paint bucket, color picker, text color",
  "Column": "single column | field, attribute",
  "Columns": "columns | fields, table columns",
  "ColumnSplit": "split column | divide, separate columns",
  "Command": "command | cmd key, keyboard, shortcut",
  "CommandPalette": "command palette | quick actions, search",
  "Compass": "discovery | explore, navigate, browse",
  "Connect": "Partner Connect | Platform | connect, integrate, link",
  "Copy": "copy | copy, duplicate, replicate",
  "CreditCard": "payment method | subscription, billing",
  "Cursor": "cursor | pointer, selection, select",
  "CursorClick": "click | select, tap, interact",
  "CursorType": "text cursor | I-beam, text select, type mode",
  "CustomApp": "App | Workspace | Custom app, Databricks Apps",
  "DAG": "Lineage | Unity Catalog | DAG, data flow, dependency graph",
  "DAGHorizontal": "horizontal DAG | Lakeflow | left-to-right flow, dependency flow",
  "DAGVertical": "DAG | Lakeflow | vertical DAG, data flow",
  "Danger": "failure | error, critical, alert",
  "DangerFill": "failure | error, critical, alert",
  "DangerSmall": "error | failure, critical, alert",
  "Dash": "remove | minus, subtract, separator",
  "Dashboard": "Dashboard | AI/BI | report, analytics, visualizations",
  "DashboardCode": "Code dashboard | AI/BI | programmatic dashboard",
  "Data": "Catalog Explorer | Unity Catalog | data, explorer",
  "Database": "Schema | Unity Catalog | data directory, data container",
  "DatabaseClock": "Temporal Table | Unity Catalog | time travel, versioned data",
  "DatabaseImport": "import data | data load, ingest to database",
  "Decimal": "Decimal | Data Type | floating point, precision number",
  "Deprecated": "deprecated | obsolete, end of life, legacy",
  "DeprecatedSmall": "deprecated | obsolete, end of life, legacy",
  "Dollar": "cost | price, billing, money, budget",
  "DomainCirclesThree": "Domains | Unity Catalog | domain hierarchy, domain groups",
  "Domains": "Domains | Unity Catalog | data domain, business domain",
  "DotsCircle": "more | options, ellipsis",
  "Download": "download | export, save file, fetch",
  "Drag": "drag handle | grip, reorder, move",
  "ERD": "Entity Relationship | Unity Catalog | ER diagram, data model",
  "ExpandLess": "collapse | show less, fold, close",
  "ExpandMore": "expand | show more, unfold, see details",
  "FaceFrown": "negative feedback | bad, unhappy, dissatisfied",
  "FaceNeutral": "neutral feedback | okay, meh, mixed",
  "FaceSmile": "positive feedback | good, happy, satisfied",
  "File": "File | Workspace | text, doc, code",
  "FileCode": "Code File | Workspace | script, source code",
  "FileCube": "Bundle File | Workspace | script, source code",
  "FileDocument": "Document File | Workspace | text, document",
  "FileImage": "Image File | Workspace | photo, picture, media",
  "FileLock": "Restricted File | Workspace | protected, access controlled",
  "FileModel": "Model File | Workspace | ml artifact, mlflow model",
  "FileNew": "new file | create file, blank document",
  "FilePipeline": "Pipeline File | Workspace | ETL file, DLT source",
  "Filter": "filter | funnel, refine, narrow",
  "FlagPointer": "Marker | flag, milestone, waypoint",
  "Float": "Float | Data Type | floating point, decimal number",
  "Flow": "conditional logic | if-else, branching, decision",
  "Folder": "Folder | Workspace | directory, container",
  "FolderBranch": "Git folder | Workspace | git folder, versioned directory",
  "FolderBranchFill": "Git Folder | Git | git folder, versioned directory",
  "FolderCloud": "Volume folder | Unity Catalog | cloud storage, managed volume",
  "FolderCloudFilled": "Volume folder | Unity Catalog | cloud storage, managed volume",
  "FolderCube": "Bundle folder | Workspace | databricks asset bundle, DAB",
  "FolderCubeOutline": "Bundle Folder | Workspace | container",
  "FolderFill": "Folder | Workspace | directory, container",
  "FolderHome": "Home Folder | Workspace | personal directory, root",
  "FolderNew": "new folder | create directory",
  "FolderNode": "Linked Folder | Workspace | folder in tree, connected",
  "FolderOpen": "Opened folder | expanded directory, browse contents",
  "FolderOpenBranch": "Open git folder | expanded git directory",
  "FolderOpenCloud": "Open volume folder | expanded cloud directory",
  "FolderOpenCube": "Open Bundle Folder | asset bundle",
  "FolderOpenPipeline": "Open pipeline folder | expanded DLT directory",
  "FolderOutlinePipeline": "Pipeline Folder | Workspace | DLT directory",
  "FolderSolidPipeline": "Pipeline folder | Lakeflow | DLT directory",
  "Font": "font | typography, typeface, text style",
  "Fork": "branch | repos, git, split, diverge",
  "ForkHorizontal": "branch | repos, git, split, diverge",
  "Fullscreen": "expand window | maximize, presentation mode",
  "FullscreenExit": "exit fullscreen | minimize, restore size",
  "Function": "Function | Unity Catalog | UDF, formula, fx",
  "Gavel": "Judges | AI | rules, policy, compliance",
  "Gear": "settings | config, preferences",
  "GearFill": "settings | config, preferences",
  "GenieCode": "Genie code | AI/BI | generative, agentic, AI query",
  "GenieDeepResearch": "Deep Research | AI/BI | genie analysis, deep dive",
  "Gift": "What's New | Platform | new feature, release, announcement",
  "GitCommit": "commit | repos, git, save version",
  "Globe": "Account | Unity Catalog | world, public, web, global",
  "Grid": "grid view | tile view, card layout, gallery",
  "GridDash": "placeholder | empty, skeleton, wireframe",
  "Group": "group | cluster, bundle, aggregate",
  "H1": "heading 1 | title, largest heading",
  "H2": "heading 2 | subtitle, section heading",
  "H3": "heading 3 | subsection heading",
  "H4": "heading 4 | minor heading",
  "H5": "heading 5 | small heading",
  "H6": "heading 6 | smallest heading",
  "Hash": "ID | Platform | hash, identifier, number sign",
  "History": "log | recent, activity, audit",
  "Home": "User root folder | Workspace | home, start, root",
  "Image": "Image | Workspace | picture, photo, graphic, visual, media",
  "IndentDecrease": "outdent | decrease indent, shift left",
  "IndentIncrease": "indent | increase indent, shift right",
  "Infinity": "unlimited | infinite, no limit, unbounded",
  "Info": "info | information, help, hint, tooltip",
  "InfoBook": "Instructions | AI/BI | knowledge base, review queue, Genie setup",
  "InfoFill": "info | information, help, hint, tooltip",
  "InfoSmall": "info | information, help, hint, tooltip",
  "Ingestion": "Connectors | Lakeflow | pipeline input, ingest, ETL",
  "Italic": "italic | emphasis, slanted text",
  "JoinOperator": "Join | join tables, merge, combine",
  "Key": "Secret | Unity Catalog | key, credential, access key, encryption",
  "Keyboard": "keyboard shortcuts | hotkeys, key bindings",
  "Layer": "Feature Table | AI | layers, stack, Feature Store",
  "LayerGraph": "Feature graph | AI | feature lineage, feature dependencies",
  "Leaf": "Environment | Platform | green, nature, sustainable",
  "LetterFormat": "text format | font style, letter case",
  "Letters": "String | Data Type | text, varchar, characters",
  "LettersNumbers": "Alphanumeric | Data Type | mixed type, text+numbers",
  "Libraries": "Library | Compute | packages, dependencies, jar, whl",
  "Lifesaver": "Help | Platform | support, rescue, life ring",
  "Lightbulb": "idea | tip, suggestion, insight",
  "Lightning": "Managed tables | Unity Catalog | lightning, bolt, quick, instant",
  "LightningCircleFill": "serverless | instant, auto-provisioned",
  "LinearLine": "Linear interpolation | AI/BI | straight line chart, trend",
  "Link": "copy link | hyperlink, URL, chain link",
  "LinkOff": "unlink | disconnect, remove link, detach",
  "List": "list | bullet list, items, line items, rows",
  "ListBorder": "bordered list | list box, contained list",
  "ListClear": "clear list | remove all, empty list",
  "ListNumber": "numbered list | ordered list, ol, steps",
  "Loading": "loading | spinner, progress, waiting",
  "Lock": "lock | secure, protected, restricted, ACL",
  "LockFill": "locked | secure, protected, restricted",
  "LockShare": "share access | grant permission, share credentials",
  "LockUnlocked": "unlock | unsecure, open access, remove restriction",
  "Loop": "retry | loop, repeat, iterate, re-run",
  "Mail": "mail | message, notification, invite",
  "Map": "Map | Data Type | location, geography, spatial",
  "Markdown": "Markdown | md, formatted text",
  "MCP": "MCP | AI | model connection protocol, tool server",
  "Measure": "Metric | AI/BI | measure, KPI, metric definition",
  "Megaphone": "Announcement | Platform | broadcast, news, release note",
  "Menu": "menu | hamburger, navigation toggle, three lines",
  "MinusCircle": "remove | minus, subtract, exclude, decrease",
  "MinusCircleFill": "remove | minus, subtract, exclude, decrease",
  "MinusCircleSmall": "remove | subtract, decrease, minus",
  "MinusSquare": "remove | subtract, exclude, minus",
  "Models": "Model | Unity Catalog | ml model, model registry, mlflow",
  "MonotoneLine": "Monotone interpolation | AI/BI | smooth curve, spline",
  "Moon": "dark mode | night mode, dark theme",
  "NeonProject": "Neon Project | Lakebase | external project, integration",
  "NewChat": "new conversation | new chat, start thread",
  "NewWindow": "open | external link, pop out, new tab",
  "No": "denied | blocked, forbidden, not allowed, prohibited",
  "Notebook": "Notebook | Workspace | cell based doc, data science",
  "NotebookPipeline": "Pipeline notebook | Lakeflow | DLT notebook",
  "Notification": "Notification | Platform | bell, alert, notify",
  "NotificationOff": "mute notifications | alerts off, silence",
  "NumberFormat": "number format | numeric display, decimal places",
  "Numbers": "Number | Data Type | integer, digits",
  "Office": "Organization | Unity Catalog | building, enterprise",
  "Overflow": "context menu | more, kebab menu, ellipsis",
  "PageBottom": "scroll to bottom | jump to end, last item",
  "PageFirst": "first page | jump to start, beginning",
  "PageLast": "last page | jump to end, final page",
  "PageTop": "scroll to top | jump to start, first item",
  "PanelDocked": "dock panel | attach panel, pin sidebar",
  "PanelFloating": "float panel | detach panel, overlay",
  "Paperclip": "attach | attachment, file upload, add file",
  "Pause": "pause | hold, suspend, pause job",
  "Pencil": "edit | edit, write, modify, rename, compose",
  "PencilFill": "edit | modify, write, compose",
  "PencilSparkle": "AI edit | smart edit, AI-assisted writing",
  "PieChart": "Pie chart | AI/BI | donut, proportion, percentage chart",
  "Pin": "pin | anchor, stick, keep visible",
  "PinCancel": "unpin | remove pin, unstick",
  "PinFill": "pinned | anchored, stuck, kept visible",
  "Pipeline": "ETL Pipeline | Lakeflow | data flow, data engineering",
  "PipelineCode": "Pipeline Code | Lakeflow | DLT source code",
  "PipelineCube": "Bundle Pipeline | Lakeflow | DLT with bundles",
  "Play": "run | execute, start, launch",
  "PlayCircle": "run | execute, start, play",
  "PlayCircleFill": "run | execute, start, play",
  "PlayDouble": "run all | execute all, batch run",
  "PlayMultiple": "run all | execute batch, run selected",
  "Plug": "Connection | Platform | plugin, connector, API, integration",
  "Plus": "add new | create, new, insert, plus, +",
  "PlusCircle": "add | create, new, plus",
  "PlusCircleFill": "add | create, new, plus",
  "PlusCircleSmall": "add | create, new, plus",
  "PlusMinusSquare": "increment/decrement | plus minus, counter, stepper",
  "PlusSquare": "add new | create, new, insert, plus, +",
  "PositionBottom": "position bottom | align bottom, dock bottom",
  "PositionLeft": "position left | align left, dock left",
  "PositionRight": "position right | align right, dock right",
  "PositionTop": "position top | align top, dock top",
  "PullRequest": "pull request | PR, merge request, code review",
  "Puzzle": "Integration | Platform | plugin, extension, add-on",
  "Query": "Query | Workspace | sql query, editor, code file",
  "QueryEditor": "SQL Editor | Workspace | query editor, IDE, authoring",
  "QuestionMark": "question | help, FAQ, support",
  "QuestionMarkFill": "question | help, FAQ, support",
  "Radio": "radio | single select, option, choice",
  "ReaderMode": "reader view | read mode, focus mode, clean view",
  "Redo": "redo | redo, ctrl+Y, repeat",
  "Refresh": "refresh | reload, sync, retry, re-fetch",
  "RefreshPlay": "restart | re-run, refresh and play",
  "RefreshX": "sync failed | refresh error, reload failed",
  "Reply": "reply | respond, answer, thread",
  "Resize": "resize | scale, adjust size, drag to resize",
  "RichText": "Rich text | formatted text, WYSIWYG",
  "Robot": "Playground | bot, service principal, AI agent",
  "Rocket": "deploy | Workspace | launch, ship, go live",
  "Rows": "rows | horizontal layout, row view",
  "Run": "run | execute, start, trigger",
  "Running": "running | in progress, active, spinning",
  "Save": "save | persist, store, ctrl+S",
  "SaveClock": "auto-saved | save history, version, last saved",
  "Schema": "Tree | Unity Catalog | data structure, DDL",
  "School": "training | education, academy, learning",
  "Search": "search | keyword search, find, lookup, discover",
  "SearchData": "Preview data | Unity Catalog | search, find, query data",
  "Send": "send | submit, dispatch",
  "Share": "share | distribute, send to",
  "Shield": "Security | Platform | protection, governance, firewall, compliance",
  "ShieldCheck": "Governed | Unity Catalog | secured, verified, compliant",
  "ShieldOff": "unprotected | no governance, insecure, ungoverned",
  "Shortcut": "shortcut | keyboard shortcuts, hotkey, key binding",
  "Sidebar": "show panel | expand sidebar, open sidebar",
  "SidebarAuto": "auto sidebar | smart sidebar, auto-hide",
  "SidebarClosed": "sidebar closed | panel hidden, sidebar off",
  "SidebarCollapse": "hide panel | collapse sidebar, minimize sidebar",
  "SidebarExpand": "show panel | expand sidebar, open sidebar",
  "SidebarOpen": "sidebar open | panel visible, sidebar on",
  "SidebarSync": "sync sidebar | refresh navigation",
  "SlashSquare": "command palette | slash command, quick action",
  "Sliders": "adjust | sliders, controls, tuning, settings",
  "SortAscending": "sort ascending | A to Z, low to high, sort up",
  "SortCustomHorizontal": "custom sort | manual sort, drag sort horizontal",
  "SortCustomVertical": "custom sort | manual sort, drag sort",
  "SortDescending": "sort descending | Z to A, high to low, sort down",
  "SortHorizontalAscending": "sort ascending | low to high, A-Z",
  "SortHorizontalDescending": "sort descending | high to low, Z-A",
  "SortLetterHorizontalAscending": "sort A-Z | alphabetical ascending",
  "SortLetterHorizontalDescending": "sort Z-A | alphabetical descending",
  "SortLetterUnsorted": "unsorted | no sort, default order",
  "SortLetterVerticalAscending": "sort A-Z vertical | alphabetical ascending",
  "SortLetterVerticalDescending": "sort Z-A vertical | alphabetical descending",
  "SortUnsorted": "sort | unsorted, no sort, default order",
  "Sparkle": "Genie assistant | AI/BI | assistant, genie",
  "SparkleDouble": "agentic | genie, generate, assistant",
  "SparkleDoubleFill": "agentic | genie, agent mode, AI active",
  "SparkleFill": "Genie assistant | AI/BI | assistant, genie",
  "SparkleRectangle": "Genie Space | AI/BI | data chat, assistant, natural language conversation",
  "SpeechBubble": "Feedback | Platform | comment, chat, message",
  "SpeechBubblePlus": "new comment | add feedback, start thread",
  "SpeechBubbleQuestionMark": "help | support, FAQ, ask question",
  "SpeechBubbleQuestionMarkFill": "Help | support, FAQ, ask a question",
  "SpeechBubbleStar": "Featured comment | highlighted feedback, top comment",
  "Speedometer": "Performance | Platform | speed, metrics, benchmarking",
  "Star": "favorite | starred, important",
  "StarFill": "favorited | starred, bookmarked",
  "StepAfterLine": "Step-after interpolation | AI/BI | staircase right",
  "StepBeforeLine": "Step-before interpolation | AI/BI | staircase left",
  "Stop": "step | terminate, abort, cancel, kill, end",
  "StopCircle": "step | terminate, abort, cancel, kill, end",
  "StopCircleFill": "stop | terminate, abort, cancel",
  "StoredProcedure": "Stored procedure | Unity Catalog | function, routine, sproc",
  "Storefront": "Marketplace | Platform | data shop, storefront, data exchange",
  "Stream": "Streaming | real-time, live data, event stream",
  "StrikeThrough": "strikethrough | cross out, delete text",
  "Sun": "light mode | day mode, light theme",
  "Sync": "sync | refresh, synchronize",
  "SyncSmall": "syncing | synchronizing, refreshing",
  "SyncToFile": "sync to file | export, save externally, file transfer",
  "Table": "Table | Unity Catalog | table, data",
  "TableAsterisk": "select all columns | wildcard, select *, star",
  "TableClock": "Temporal table | Unity Catalog | time travel, table history",
  "TableCombine": "Joined table | merge, union, combine datasets",
  "TableGlasses": "Table Views | Unity Catalog | views, dataset",
  "TableGlobe": "External table | Unity Catalog | foreign table, remote data",
  "TableLightning": "Materialized View | Unity Catalog | MV, precomputed, auto-refreshed",
  "TableMeasure": "Metric view | AI/BI | measure, KPI, aggregation",
  "TableModel": "Model table | AI | model registry, experiment table",
  "TableStream": "Streaming Table | Lakeflow | real-time table, live data",
  "TableVector": "Vector Index | AI | embeddings, similarity search",
  "TableView": "Table View | Unity Catalog | tabular display, data grid",
  "Tag": "Tag | Unity Catalog | label, category, governance tag",
  "Target": "Focus | scope, destination",
  "Terminal": "Web Terminal | Compute | console, CLI, shell",
  "Text": "add text | string, characters",
  "TextBox": "Text widget | AI/BI | text box, text input, label",
  "TextJustify": "justify text | full width, block align",
  "TextUnderline": "underline | underline text",
  "ThreeDots": "typing | loading dots, ellipsis, in progress",
  "ThumbsDown": "dislike | negative feedback, reject",
  "ThumbsUp": "like | positive feedback, approve",
  "Token": "Access token | IAM | credential, auth token, PAT",
  "Trash": "delete | remove, trash, discard, destroy",
  "Tree": "Cluster | Platform | compute, nested structure",
  "Trending": "trending | popular, rising, hot, flame",
  "Triangle": "marker | pointer, caret, sort indicator",
  "Underline": "underline | underline text, emphasis",
  "Undo": "undo | revert, go back, ctrl+Z, rollback",
  "Upload": "upload | import, push to volume",
  "Usb": "Connector | Platform | USB, hardware, peripheral",
  "User": "User | IAM | person, profile",
  "UserBadge": "User | IAM | credentialed user, role indicator",
  "UserCircle": "User profile | IAM | avatar, account, identity",
  "UserGroup": "Group | IAM | team, people, members",
  "UserGroupFill": "Group | IAM | team, people, members",
  "UserKey": "Service principal | IAM | API key user, machine identity",
  "UserOutline": "User | IAM | person, profile, outline",
  "UserShield": "Admin user | IAM | admin, security admin, privileged",
  "UserSparkle": "AI user | AI/BI | genie, agent",
  "UserTeam": "Team | IAM | team members, group",
  "Visible": "show | visible, eye, reveal, view",
  "VisibleFill": "visible | showing, eye on, revealed",
  "VisibleOff": "hide | invisible, eye off, conceal, hidden",
  "Warning": "warning | In Component | caution, !, alert, attention",
  "WarningFill": "warning | caution, !, alert, attention",
  "WorkflowCode": "Code workflow | Lakeflow | programmatic job",
  "WorkflowCube": "Bundle pipeline | Lakeflow | asset bundle, pipeline",
  "Workflows": "Jobs | Lakeflow | DAG, task flow, orchestration, automation",
  "Workspaces": "Workspace | project space, working area",
  "Wrench": "config | tools, fix, repair",
  "WrenchSparkle": "AI fix | smart repair, AI tools, auto-fix",
  "XCircle": "error | error, invalid, rejected",
  "XCircleFill": "error | error, invalid, rejected",
  "ZaHorizontal": "sort Z-A | reverse alphabetical, descending text",
  "ZaVertical": "sort Z-A | reverse alphabetical vertical, descending text",
  "ZoomIn": "zoom in | magnify, enlarge",
  "ZoomMarqueeSelection": "marquee select | area select, box select, lasso",
  "ZoomOut": "zoom out | shrink, reduce",
  "ZoomToFit": "fit to screen | auto zoom, fit view",
}
